language: objective-c
osx_image: xcode10.0
env:
  global:
  - LC_CTYPE=en_US.UTF-8
  - LANG=en_US.UTF-8
  - PROJECT=PrediKit.xcodeproj
  - iOS_FRAMEWORK_SCHEME="PrediKit iOS"
  - OSX_FRAMEWORK_SCHEME="PrediKit OSX"
  - tvOS_FRAMEWORK_SCHEME="PrediKit tvOS"
  - watchOS_FRAMEWORK_SCHEME="PrediKit watchOS"
  - iOS_SDK=iphonesimulator11.2
  - OSX_SDK=macosx10.13
  - tvOS_SDK=appletvsimulator11.2
  - watchOS_SDK=watchsimulator4.2
before_install:
    - 'echo ''gem: --no-ri --no-rdoc'' > ~/.gemrc'
    - gem install xcpretty -N
    - gem install slather cocoapods
script:
  - set -o pipefail
  - xcodebuild -version
  - xcodebuild -showsdks

  # Build Framework in Debug and Run Tests if specified
  - if [ $RUN_TESTS == "YES" ]; then
      xcodebuild -project "$PROJECT" -scheme "$SCHEME" -sdk "$SDK" -destination "$DESTINATION" -configuration Debug ONLY_ACTIVE_ARCH=NO ENABLE_TESTABILITY=YES test | xcpretty -c;
    else
      xcodebuild -project "$PROJECT" -scheme "$SCHEME" -sdk "$SDK" -destination "$DESTINATION" -configuration Debug ONLY_ACTIVE_ARCH=NO build | xcpretty -c;
    fi

  # Run `pod lib lint` if specified
  - if [ $POD_LINT == "YES" ]; then
      pod lib lint --quick;
    fi
after_success:
    - slather
